In [1]:
import numpy as np

In [2]:
A = np.array([1,1,1])
B = np.array([2,2,2])

In [3]:
C = np.vstack((A,B)) #上下合并数组

In [4]:
D = np.hstack((A,B))#左右合并序列，成矩阵

In [5]:
print(A.shape,C.shape)

(3,) (2, 3)


In [6]:
print(D)

[1 1 1 2 2 2]


In [7]:
print(A[np.newaxis,:])#横向增加一个维度

[[1 1 1]]


In [8]:
print(A[:,np.newaxis])#纵向增加一个维度

[[1]
 [1]
 [1]]


In [9]:
A.reshape((3,1))

array([[1],
       [1],
       [1]])

In [10]:
C = np.concatenate((A,B,B,A),axis = 1)#函数合并矩阵

In [11]:
C

array([1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 1, 1])

In [13]:
print(C)

[1 1 1 2 2 2 2 2 2 1 1 1]


In [14]:
A = np.arange(12).reshape((3,4))

In [15]:
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [17]:
print(np.split(A,3,axis = 0))#横向分割,3代表分成的块数，axis是分割的维度

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


In [20]:
print(np.array_split(A,3,axis = 1))#不均衡分割

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]


In [23]:
print(np.vsplit(A,3))

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


In [24]:
print(np.hsplit(A,2))

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


In [1]:
import numpy as np

In [21]:
arr1 = np.array([7,8,9])

In [7]:
arr1.shape

(4,)

In [14]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [11]:
arr1.sort()
arr1

array(['1', '2', '3', 'a'], dtype='<U1')

In [15]:
arr2.sort()
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
print(arr2.max())

9


In [22]:
print(arr1.min())

7


In [24]:
arr2[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [25]:
import pandas as pd

In [28]:
ser = pd.Series([1,2,3],index = ["a","b","c"])

In [29]:
ser

a    1
b    2
c    3
dtype: int64

In [38]:
df1 = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],index = ["a","b","c"],columns=["A","B","C"])

In [39]:
df1

A  B  C
a  1  2  3
b  4  5  6
c  7  8  9

In [41]:
df1.transpose()

a  b  c
A  1  4  7
B  2  5  8
C  3  6  9

In [43]:
df1.T

a  b  c
A  1  4  7
B  2  5  8
C  3  6  9