# 3逻辑回归

In [1]:
import pandas as pd
import numpy as np

In [4]:
filename = "inputData/loandata.xls"

In [6]:
data = pd.read_excel(filename)
data.head()

年龄  教育  工龄  地址   收入   负债率      信用卡负债      其他负债  违约
0  41   3  17  12  176   9.3  11.359392  5.008608   1
1  27   1  10   6   31  17.3   1.362202  4.000798   0
2  40   1  15  14   55   5.5   0.856075  2.168925   0
3  41   1  15  14  120   2.9   2.658720  0.821280   0
4  24   2   2   0   28  17.3   1.787436  3.056564   1

In [8]:
X_data = data.drop(["违约"],axis=1)
print(X_data.head())

   年龄  教育  工龄  地址   收入   负债率      信用卡负债      其他负债
0  41   3  17  12  176   9.3  11.359392  5.008608
1  27   1  10   6   31  17.3   1.362202  4.000798
2  40   1  15  14   55   5.5   0.856075  2.168925
3  41   1  15  14  120   2.9   2.658720  0.821280
4  24   2   2   0   28  17.3   1.787436  3.056564


In [9]:
y_data = np.ravel(data[["违约"]])
print(y_data[:5])

[1 0 0 0 1]


In [12]:
from sklearn.linear_model import RandomizedLogisticRegression as RLR

In [13]:
rlr = RLR()
rlr.fit(X_data,y_data)

RandomizedLogisticRegression(C=1, fit_intercept=True, memory=None, n_jobs=1,
               n_resampling=200, normalize=True, pre_dispatch='3*n_jobs',
               random_state=None, sample_fraction=0.75, scaling=0.5,
               selection_threshold=0.25, tol=0.001, verbose=False)

In [14]:
rlr.scores_

array([0.11 , 0.075, 0.99 , 0.385, 0.   , 0.995, 0.535, 0.04 ])

In [15]:
print(rlr.scores_)

[0.11  0.075 0.99  0.385 0.    0.995 0.535 0.04 ]


In [16]:
print(rlr.get_support())

[False False  True  True False  True  True False]


In [17]:
data.columns

Index(['年龄', '教育', '工龄', '地址', '收入', '负债率', '信用卡负债', '其他负债', '违约'], dtype='object')

In [18]:
X2_data = data.drop(["年龄","教育","收入","其他负债","违约"],axis=1)
X2_data.head()

工龄  地址   负债率      信用卡负债
0  17  12   9.3  11.359392
1  10   6  17.3   1.362202
2  15  14   5.5   0.856075
3  15  14   2.9   2.658720
4   2   0  17.3   1.787436

In [19]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X2_data,y_data,random_state=1)
print(X_train.shape)
print(X_test.shape)


(525, 4)
(175, 4)


In [23]:
from sklearn.linear_model import LogisticRegression as LR

In [24]:
lr = LR()#可以加参数

In [25]:
lr.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [26]:
print("训练模型自变量的参数为:",lr.coef_)
print("训练模型的截距为:",lr.intercept_)

训练模型自变量的参数为: [[-0.2247587  -0.07545825  0.08622488  0.54829573]]
训练模型的截距为: [-0.90003215]


In [29]:
lr.predict(X_test)

array([0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0],
      dtype=int64)

In [30]:
print("模型的平均正确率为:",lr.score(X_test,y_test))

模型的平均正确率为: 0.8342857142857143


# 4 朴素贝叶斯

In [31]:
import numpy as np
import pandas as pd
import seaborn as sns

In [32]:
iris = sns.load_dataset("iris")

In [33]:
iris.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [35]:
X_iris = iris.drop(["species"],axis=1)
print(X_iris.head())

   sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2


In [37]:
y_iris = np.ravel(iris["species"])
print(y_iris)

['setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'setosa' 'setosa' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'v

In [38]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X_iris,y_iris,random_state=1)

In [39]:
print(X_train.head())

     sepal_length  sepal_width  petal_length  petal_width
54            6.5          2.8           4.6          1.5
108           6.7          2.5           5.8          1.8
112           6.8          3.0           5.5          2.1
17            5.1          3.5           1.4          0.3
119           6.0          2.2           5.0          1.5


In [40]:
print(X_test.shape)

(38, 4)


In [41]:
print(y_train.shape)
print(y_test.shape)

(112,)
(38,)


In [42]:
from sklearn.naive_bayes import GaussianNB
model_GaussianNB = GaussianNB().fit(X_train,y_train)
y_predict_GaussianNB = model_GaussianNB.predict(X_test)

In [43]:
y_predict_GaussianNB

array(['setosa', 'versicolor', 'versicolor', 'setosa', 'virginica',
       'versicolor', 'virginica', 'setosa', 'setosa', 'virginica',
       'versicolor', 'setosa', 'virginica', 'versicolor', 'versicolor',
       'setosa', 'versicolor', 'versicolor', 'setosa', 'setosa',
       'versicolor', 'versicolor', 'virginica', 'setosa', 'virginica',
       'versicolor', 'setosa', 'setosa', 'versicolor', 'virginica',
       'versicolor', 'virginica', 'versicolor', 'virginica', 'virginica',
       'setosa', 'versicolor', 'setosa'], dtype='<U10')

In [44]:
import pandas as pd

In [50]:
z_data = {"sepal_length":[5],"sepal_width":[3],"petal_length":[3],"petal_width":[1.8]}
z_data = pd.DataFrame(z_data,columns=["sepal_length","sepal_width","petal_length","petal_width"])

In [51]:
z_data

sepal_length  sepal_width  petal_length  petal_width
0             5            3             3          1.8

In [52]:
z_model  = model_GaussianNB.predict(z_data)

In [53]:
np.mean(y_predict_GaussianNB==y_test)

0.9736842105263158

In [54]:
from sklearn.naive_bayes import BernoulliNB
model_BernoulliNB = BernoulliNB().fit(X_train,y_train)
y_predict_BernoulliNB = model_BernoulliNB.predict(X_test)


In [55]:
np.mean(y_predict_BernoulliNB==y_test)

0.23684210526315788

In [64]:
from sklearn.naive_bayes import MultinomialNB
model_MultinomialNB = MultinomialNB().fit(X_train,y_train)
y_predict_MultionmialNB = model_MultinomialNB.predict(X_test)
np.mean(y_predict_MultionmialNB==y_test)

0.5789473684210527